import { renderMarkdown } from "@/lib/markdown";
import { generatePrompt } from "@/lib/prompt-engine";
import type { Answers } from "@/lib/questions";

/**
 * A real sample output, generated by the same engine the product uses.
 * Nothing here is hand-written marketing copy pretending to be a result.
 */
const SAMPLE: Answers = {
  idea: "Un outil qui transforme les appels clients en compte-rendus structurés poussés automatiquement dans le CRM",
  problem:
    "Les commerciaux passent 40 minutes par jour à réécrire leurs notes d'appel, et la moitié des informations n'arrive jamais dans le CRM",
  audience: "b2b-smb",
  competitor: "Un bloc-notes et du copier-coller dans HubSpot",
  primaryColor: "#7C5CFF",
  mode: "dark",
  visualStyle: "minimal",
  imageStyle: "screenshots",
  typography: "modern-sans",
  mrrTarget: "10000",
  pricingModel: "subscription",
  arpu: "49",
  timeline: "1m",
  stack: "next-postgres",
  auth: "email-password",
  payments: "stripe",
  skill: "intermediate",
  ai: "claude",
  features: ["dashboard", "onboarding", "integrations"],
  language: "fr",
  tone: "direct",
};

export function BriefPreview() {
  const result = generatePrompt(SAMPLE);
  const excerpt = result.markdown.slice(0, 3200);
  const html = renderMarkdown(excerpt);

  return (
    <div className="surface relative overflow-hidden">
      <div className="flex items-center gap-2 border-b border-white/[0.07] px-4 py-3">
        <span className="h-2.5 w-2.5 rounded-full bg-white/15" />
        <span className="h-2.5 w-2.5 rounded-full bg-white/15" />
        <span className="h-2.5 w-2.5 rounded-full bg-white/15" />
        <span className="ml-3 font-mono text-[12px] text-ink-500">
          brief-{result.productName.toLowerCase()}.md
        </span>
        <span className="ml-auto rounded-md border border-white/[0.09] px-2 py-0.5 font-mono text-[11px] text-ink-400">
          {result.wordCount.toLocaleString("fr-FR")} mots
        </span>
      </div>

      <div className="relative max-h-[520px] overflow-hidden px-5 pt-6 sm:px-8">
        <div className="prompt-doc" dangerouslySetInnerHTML={{ __html: html }} />
        <div className="pointer-events-none absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-ink-950 via-ink-950/85 to-transparent" />
      </div>

      <div className="relative -mt-10 px-5 pb-6 text-center sm:px-8">
        <p className="text-[13px] text-ink-400">
          Extrait réel · le brief complet fait {result.wordCount.toLocaleString("fr-FR")} mots et 12 sections
        </p>
      </div>
    </div>
  );
}
